#Navigate to the directory ,where USDV.csv is saved
USDA = read.csv("USDA.csv")
USDA
#Extercating dates in R
mvt$Month = months(DateConvert)
mvt$Weekday =weekdays(DateConvert)
mvt$Date = DateConvert
table(mvt$Date)
table(mvt$Month,mvt$Arrest)
boxplot(mvt$Date,mvt$Arrest)
hist(mvt$Date,breaks =100)
we'll take a look at how the stock dynamics of these companies have changed over time.__________21__06___assignment1__part2__
IBM=read.csv("IBMStock.csv")
GE =read.csv("GEStock.csv")
ProcterGamble  =read.csv("ProcterGambleStock.csv")
CocaCola = read.csv("CocaColaStock.csv")
Boeing = read.csv("BoeingStock.csv")
IBM$Date = as.Date(IBM$Date,"%m/%d/%y")
GE$Date = as.Date(GE$Date, "%m/%d/%y")
CocaCola$Date = as.Date(CocaCola$Date, "%m/%d/%y")
ProcterGamble$Date = as.Date(ProcterGamble$Date, "%m/%d/%y")
Boeing$Date = as.Date(Boeing$Date, "%m/%d/%y")
str(IBM)
min(IBM$Date)
min(GE$Date)
 max(IBM$Date)
 max(GE$Date)
 mean(IBM$StockPrice)
min(GE$StockPrice)
max(CocaCola$StockPrice)
summary(Boeing)
 sd(ProcterGamble$StockPrice)
plot(CocaCola$Date,CocaCola$StockPrice)
plot(CocaCola$Date,CocaCola$StockPrice,type= "l")
lines(ProcterGamble$Date, ProcterGamble$StockPrice)
plot(CocaCola$Date,CocaCola$StockPrice,type= "l",col="red")
lines(ProcterGamble$Date, ProcterGamble$StockPrice,col="blue")
lines(ProcterGamble$Date, ProcterGamble$StockPrice,col="blue",lty=2)
abline(v=as.Date(c("2003-03-01")),lw=2)
plot(CocaCola$Date[301:432],CocaCola$StockPrice[301:432],type="l",col="red",ylim=c(0,210))
lines(ProcterGamble$Date, ProcterGamble$StockPrice,col="blue")
lines(IBM$Date, IBM$StockPrice,col="orange")
lines(GE$Date, GE$StockPrice,col="purple")
lines(Boeing$Date, Boeing$StockPrice,col="green")
abline(v=as.Date(c("2004-01-01")),lw=3)
abline(v=as.Date(c("2005-01-01")),lw=3)
tapply(IBM$StockPrice,months(IBM$Date),mean,na.rm=TRUE)
mean(IBM$StockPrice)

#Demographics and employement in the United States.
CPS = read.csv("CPSData.csv")
str(CPS)
summary(CPS)
sort(table(CPS$Industry))
sort(table(CPS$State))
table(CPS$Race,CPS$Hispanic)
summary(CPS)
table(CPS$Region,is.na(CPS$Married))
tapply(is.na(CPS$MetroAreaCode),CPS$State,mean)
MetroAreaMap = read.csv("MetroAreaCodes.csv")
str(MetroAreaMap)
str(CountryMap)
CPS=merge(CPS,MetroAreaMap,by.x="MetroAreaCode",by.y="Code",all.x=TRUE)
table(is.na(CPS$MetroArea)
table(CPS$MetroArea)
sort(tapply(CPS$Hispanic,CPS$MetroArea,mean))
sort(tapply(CPS$Race=="Asian",CPS$MetroArea,mean))
sort(tapply(CPS$Education == "No high school diploma", CPS$MetroArea, mean,na.rm=TRUE))
CPS = merge(CPS,CountryMap,by.x="CountryOfBirthCode",by.y="Code",all.x=TRUE)
summary(CPS$Country)
 table(CPS$MetroArea,CPS$Country=="India")
sort(tapply(CPS$Country=="India",CPS$MetroArea,sum,na.rm=TRUE))
sort(tapply(CPS$Country == "India", CPS$MetroArea, sum))


